language:
  - bash

services:
  - docker

sudo: true

jobs:
  include:
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 5/java blackduck blackduck:5 blackduck:5.3 blackduck:5.3.2
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 5/node blackduck:node blackduck:5-node blackduck:5.3-node blackduck:5.3.2-node

